#Comentários sobre o desafio

###Boa noite, pessoal. Eu demorei mais para fazer o desafio por falta de confiança do que qualquer outra questão, percebi durante o processo que eu realmente não estava preparado para criar um projeto desse, ainda sinto que não estou, mas eu acho que finalizei (não tenho certeza absoluta, sinto que falta algo).
###Aprendi muito no proesso e ao finalizar eu percebi que agora eu já sei muito mais do que antes, inclusive eu consigo olhar o código e ver sentido no que fiz. Eu usei como base um código já pronto que estava disponível no próprio site, e como dica do Eduardo eu usei o chatgpt para me dar dicar e melhorar o código. com isso eu consegui finalizar e tanto o código ficou diferente que o valor também foi, ao que eu vejo eu estaria dentro do top20, chegando no objetivo do SNA.
###No processo de desenvolvimento tive algumas ideias diferentes do autor para crair um código possivelmente mais preciso, mas ainda não executei. A ideia é separar todas as habilidades exigidas e relacionar as que mais se relacionam com os maiores salários e assim determinar níveis de importância para as habilidades mais exigidas, como sendo uma nova variável. Planejo tentar implementar isso no meu código mas em uma parte separada e não em outro código, conforme eu for tentando que parou para ler isso poderá acompanhar também.
###Fora isso, como eu disse agora me sinto mais confiante em pelo menos entender a estrutura de uma modelo de Ml, por isso vou tentar fazer pelo menos 1 projeto por mês que eu encontrar no Kaggle ou mesmo no Machine Hack para seguir treinando e paralelamente começar a aplicar os conhecimentos nas minhas atividades dentro do trabalho.

#Início

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

data_salary = pd.read_excel('/content/drive/MyDrive/Bases/Hackathon/sample_submission.xlsx')

data_test = pd.read_csv('/content/drive/MyDrive/Bases/Hackathon/Final_Test_Dataset.csv', sep=",")

data_train = pd.read_csv('/content/drive/MyDrive/Bases/Hackathon/Final_Train_Dataset.csv')

#Comentários

###data_test['job_type'].unique() #padronizar a palavra analytics, usar todas em lower

###data_test['job_description'].unique() - coluna não utilizada para a análise

###data_test['job_desig'].unique() #retirar pontos e | das palavras listadas e padronizar tamanho para lower

###data_train['key_skills'].unique() #- retirar pontos e '' das key skills listadas e padronizar tamanho para lower

###data_test['location'].unique()

###data_train.info()

###data_salary.head()

###data_test.info() # vemos aqui que existem muitas linhas vaziar em job_type, vemos também que fora a última coluina todas são objects

#Limpeza de Colunas

###Melhornado código base

In [ ]:
#começar a corrigir as informações das colunas

#analisando as informações, o que podemos considerar importante para a criação da máquina
#são as colunas key_skills, job_desig, job_type, salary e location
#para isso é necessário fazer uma limpeza nas linhas para que a informação fiquei padronizada
#pesquisando encontrei uma forma criando uma def e transfomando a base em um df


data_train = data_train.dropna(subset=['key_skills']) #eliminando uma linha vazia da coluna
#cria com a def uma função lambda para limpar as linhas da base
def clean_skills(skl):
    skills = str(skl).lower()
    skills = re.sub(r'\W', ' ', skills)  # Substitui não palavras por espaços
    skills = re.sub(r'\s+', ' ', skills)  # Remove espaços em excesso
    return skills.strip()  # Remove espaços no início e no final

# Cria os dataframes
df_train = data_train[['key_skills', 'job_desig', 'job_description', 'location', 'job_type', 'experience', 'salary']]
df_test = data_test[['key_skills', 'job_desig', 'job_description', 'job_type', 'experience', 'location']]

# Aplica a limpeza nas colunas 'key_skills' dos dataframes
df_train['skills_cleaned'] = df_train['key_skills'].apply(clean_skills)
df_test['skills_cleaned'] = df_test['key_skills'].apply(clean_skills)

<ipython-input-311-4d9842272b01>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train['skills_cleaned'] = df_train['key_skills'].apply(clean_skills)

In [ ]:
df_train.head()

,key_skills,job_desig,job_description,location,job_type,experience,salary,skills_cleaned
0,"team skills, communication skills, analytical ...",Senior Exploit and Vulnerability Researcher,Exp: Minimum 5 years;Good understanding of IOC...,Delhi NCR(Vikas Puri),missingjobtype,5-7 yrs,6to10,team skills communication skills analytical sk...
1,"ppc, logistics, inventory management, supply c...",Head SCM,He should have handled a team of atleast 5-6 d...,Sonepat,missingjobtype,10-17 yrs,10to15,ppc logistics inventory management supply chai...
2,"HR Analytics, Employee Engagement, Training, S...",Deputy Manager - Talent Management & Leadershi...,Must be an effective communicator (written & s...,Delhi NCR,analytics,5-9 yrs,15to25,hr analytics employee engagement training succ...
3,"SQL, Javascript, Automation, Python, Ruby, Ana...",Associate Manager Data Engineering,7 - 10 years of overall experience in data e...,Bengaluru,analytics,7-10 yrs,10to15,sql javascript automation python ruby analytic...
4,"accounting, finance, cash flow, financial plan...",TS- GSA- Senior Analyst,Chartered Accountancy degree or MBA in Finance...,Gurgaon,missingjobtype,1-3 yrs,3to6,accounting finance cash flow financial plannin...

In [ ]:
#Limpando a coluna job_design
def clean_job_desig(desig):
    job_desig = desig.lower()
    job_desig = re.sub(r'[^a-z]', ' ', job_desig)
    job_desig = re.sub(r'\s+', ' ', job_desig)
    return job_desig

df_train['desig_cleaned'] = df_train['job_desig'].apply(clean_job_desig)
df_test['desig_cleaned'] = df_test['job_desig'].apply(clean_job_desig)

df_train.head()

,key_skills,job_desig,job_description,location,job_type,experience,salary,skills_cleaned,desig_cleaned
0,"team skills, communication skills, analytical ...",Senior Exploit and Vulnerability Researcher,Exp: Minimum 5 years;Good understanding of IOC...,Delhi NCR(Vikas Puri),missingjobtype,5-7 yrs,6to10,team skills communication skills analytical sk...,senior exploit and vulnerability researcher
1,"ppc, logistics, inventory management, supply c...",Head SCM,He should have handled a team of atleast 5-6 d...,Sonepat,missingjobtype,10-17 yrs,10to15,ppc logistics inventory management supply chai...,head scm
2,"HR Analytics, Employee Engagement, Training, S...",Deputy Manager - Talent Management & Leadershi...,Must be an effective communicator (written & s...,Delhi NCR,analytics,5-9 yrs,15to25,hr analytics employee engagement training succ...,deputy manager talent management leadership de...
3,"SQL, Javascript, Automation, Python, Ruby, Ana...",Associate Manager Data Engineering,7 - 10 years of overall experience in data e...,Bengaluru,analytics,7-10 yrs,10to15,sql javascript automation python ruby analytic...,associate manager data engineering
4,"accounting, finance, cash flow, financial plan...",TS- GSA- Senior Analyst,Chartered Accountancy degree or MBA in Finance...,Gurgaon,missingjobtype,1-3 yrs,3to6,accounting finance cash flow financial plannin...,ts gsa senior analyst

In [ ]:
#Limpando a coluna job_design
#na coluna job_description tem muitos valores nulos, colocar os valores vazios como missing
data_train['job_description'].fillna('missing', inplace=True)
data_test['job_description'].fillna('missing', inplace=True)

def clean_job_desc(job):
    job_desc = str(job).lower()
    job_desc = re.sub(r'[^a-z]', ' ', job_desc)
    job_desc = re.sub(r'\s+', ' ', job_desc)
    return job_desc

df_train['job_desc_cleaned'] = df_train['job_description'].apply(clean_job_desc)
df_test['job_desc_cleaned'] = df_test['job_description'].apply(clean_job_desc)

df_train.head()

,key_skills,job_desig,job_description,location,job_type,experience,salary,skills_cleaned,desig_cleaned,job_desc_cleaned
0,"team skills, communication skills, analytical ...",Senior Exploit and Vulnerability Researcher,Exp: Minimum 5 years;Good understanding of IOC...,Delhi NCR(Vikas Puri),missingjobtype,5-7 yrs,6to10,team skills communication skills analytical sk...,senior exploit and vulnerability researcher,exp minimum years good understanding of ioc ru...
1,"ppc, logistics, inventory management, supply c...",Head SCM,He should have handled a team of atleast 5-6 d...,Sonepat,missingjobtype,10-17 yrs,10to15,ppc logistics inventory management supply chai...,head scm,he should have handled a team of atleast direc...
2,"HR Analytics, Employee Engagement, Training, S...",Deputy Manager - Talent Management & Leadershi...,Must be an effective communicator (written & s...,Delhi NCR,analytics,5-9 yrs,15to25,hr analytics employee engagement training succ...,deputy manager talent management leadership de...,must be an effective communicator written spok...
3,"SQL, Javascript, Automation, Python, Ruby, Ana...",Associate Manager Data Engineering,7 - 10 years of overall experience in data e...,Bengaluru,analytics,7-10 yrs,10to15,sql javascript automation python ruby analytic...,associate manager data engineering,years of overall experience in data engineeri...
4,"accounting, finance, cash flow, financial plan...",TS- GSA- Senior Analyst,Chartered Accountancy degree or MBA in Finance...,Gurgaon,missingjobtype,1-3 yrs,3to6,accounting finance cash flow financial plannin...,ts gsa senior analyst,chartered accountancy degree or mba in finance...

In [ ]:
#seguindo a mesma base do anterior

def clean_location(loc):
    location = loc.lower()
    location = re.sub(r'[^a-z]', ' ', location)
    location = re.sub(r'\s+', ' ', location)
    return location

df_train['location_cleaned'] = df_train['location'].apply(clean_location)
df_test['location_cleaned'] = df_test['location'].apply(clean_location)

df_train.head()

,key_skills,job_desig,job_description,location,job_type,experience,salary,skills_cleaned,desig_cleaned,job_desc_cleaned,location_cleaned
0,"team skills, communication skills, analytical ...",Senior Exploit and Vulnerability Researcher,Exp: Minimum 5 years;Good understanding of IOC...,Delhi NCR(Vikas Puri),missingjobtype,5-7 yrs,6to10,team skills communication skills analytical sk...,senior exploit and vulnerability researcher,exp minimum years good understanding of ioc ru...,delhi ncr vikas puri
1,"ppc, logistics, inventory management, supply c...",Head SCM,He should have handled a team of atleast 5-6 d...,Sonepat,missingjobtype,10-17 yrs,10to15,ppc logistics inventory management supply chai...,head scm,he should have handled a team of atleast direc...,sonepat
2,"HR Analytics, Employee Engagement, Training, S...",Deputy Manager - Talent Management & Leadershi...,Must be an effective communicator (written & s...,Delhi NCR,analytics,5-9 yrs,15to25,hr analytics employee engagement training succ...,deputy manager talent management leadership de...,must be an effective communicator written spok...,delhi ncr
3,"SQL, Javascript, Automation, Python, Ruby, Ana...",Associate Manager Data Engineering,7 - 10 years of overall experience in data e...,Bengaluru,analytics,7-10 yrs,10to15,sql javascript automation python ruby analytic...,associate manager data engineering,years of overall experience in data engineeri...,bengaluru
4,"accounting, finance, cash flow, financial plan...",TS- GSA- Senior Analyst,Chartered Accountancy degree or MBA in Finance...,Gurgaon,missingjobtype,1-3 yrs,3to6,accounting finance cash flow financial plannin...,ts gsa senior analyst,chartered accountancy degree or mba in finance...,gurgaon

In [ ]:
#o job_values tem problema de NaN e diferentes formas de escrever analytics, o que foi padronizado abaixo
job_type_values = ['Analytics', 'Analytic', 'ANALYTICS', 'analytic']
replacement_value = 'analytics'

data_train['job_type'] = data_train['job_type'].fillna('missingjobtype').replace(job_type_values, replacement_value)
data_test['job_type'] = data_test['job_type'].fillna('missingjobtype').replace(job_type_values, replacement_value)

df_train.head()

,key_skills,job_desig,job_description,location,job_type,experience,salary,skills_cleaned,desig_cleaned,job_desc_cleaned,location_cleaned
0,"team skills, communication skills, analytical ...",Senior Exploit and Vulnerability Researcher,Exp: Minimum 5 years;Good understanding of IOC...,Delhi NCR(Vikas Puri),missingjobtype,5-7 yrs,6to10,team skills communication skills analytical sk...,senior exploit and vulnerability researcher,exp minimum years good understanding of ioc ru...,delhi ncr vikas puri
1,"ppc, logistics, inventory management, supply c...",Head SCM,He should have handled a team of atleast 5-6 d...,Sonepat,missingjobtype,10-17 yrs,10to15,ppc logistics inventory management supply chai...,head scm,he should have handled a team of atleast direc...,sonepat
2,"HR Analytics, Employee Engagement, Training, S...",Deputy Manager - Talent Management & Leadershi...,Must be an effective communicator (written & s...,Delhi NCR,analytics,5-9 yrs,15to25,hr analytics employee engagement training succ...,deputy manager talent management leadership de...,must be an effective communicator written spok...,delhi ncr
3,"SQL, Javascript, Automation, Python, Ruby, Ana...",Associate Manager Data Engineering,7 - 10 years of overall experience in data e...,Bengaluru,analytics,7-10 yrs,10to15,sql javascript automation python ruby analytic...,associate manager data engineering,years of overall experience in data engineeri...,bengaluru
4,"accounting, finance, cash flow, financial plan...",TS- GSA- Senior Analyst,Chartered Accountancy degree or MBA in Finance...,Gurgaon,missingjobtype,1-3 yrs,3to6,accounting finance cash flow financial plannin...,ts gsa senior analyst,chartered accountancy degree or mba in finance...,gurgaon

In [ ]:
#separando a coluna de mínimo e máximo para facilitar a leitura do algorítimo e criando a merde depois

def min_exp(exp):
    val = re.sub(r'\-', ' ', exp)
    val = val.split(' ')
    val = int(val[0])
    return val

def max_exp(exp):
    val = re.sub(r'\-', ' ', exp)
    val = val.split(' ')
    if len(val) > 1:
        val = int(val[1])
    else:
        val = None
    return val

df_train['min_exp'] = df_train['experience'].apply(min_exp)
df_train['max_exp'] = df_train['experience'].apply(max_exp)
df_test['min_exp'] = df_test['experience'].apply(min_exp)
df_test['max_exp'] = df_test['experience'].apply(max_exp)

df_train['merged'] = df_train['desig_cleaned'] + ' ' + df_train['job_desc_cleaned'] + ' ' + df_train['skills_cleaned'] + ' ' + df_train['job_type']
df_test['merged'] = df_test['desig_cleaned'] + ' ' + df_test['job_desc_cleaned'] + ' ' + df_test['skills_cleaned'] + ' ' + df_test['job_type']

df_train.head()

,key_skills,job_desig,job_description,location,job_type,experience,salary,skills_cleaned,desig_cleaned,job_desc_cleaned,location_cleaned,min_exp,max_exp,merged
0,"team skills, communication skills, analytical ...",Senior Exploit and Vulnerability Researcher,Exp: Minimum 5 years;Good understanding of IOC...,Delhi NCR(Vikas Puri),missingjobtype,5-7 yrs,6to10,team skills communication skills analytical sk...,senior exploit and vulnerability researcher,exp minimum years good understanding of ioc ru...,delhi ncr vikas puri,5,7,senior exploit and vulnerability researcher ex...
1,"ppc, logistics, inventory management, supply c...",Head SCM,He should have handled a team of atleast 5-6 d...,Sonepat,missingjobtype,10-17 yrs,10to15,ppc logistics inventory management supply chai...,head scm,he should have handled a team of atleast direc...,sonepat,10,17,head scm he should have handled a team of atle...
2,"HR Analytics, Employee Engagement, Training, S...",Deputy Manager - Talent Management & Leadershi...,Must be an effective communicator (written & s...,Delhi NCR,analytics,5-9 yrs,15to25,hr analytics employee engagement training succ...,deputy manager talent management leadership de...,must be an effective communicator written spok...,delhi ncr,5,9,deputy manager talent management leadership de...
3,"SQL, Javascript, Automation, Python, Ruby, Ana...",Associate Manager Data Engineering,7 - 10 years of overall experience in data e...,Bengaluru,analytics,7-10 yrs,10to15,sql javascript automation python ruby analytic...,associate manager data engineering,years of overall experience in data engineeri...,bengaluru,7,10,associate manager data engineering years of o...
4,"accounting, finance, cash flow, financial plan...",TS- GSA- Senior Analyst,Chartered Accountancy degree or MBA in Finance...,Gurgaon,missingjobtype,1-3 yrs,3to6,accounting finance cash flow financial plannin...,ts gsa senior analyst,chartered accountancy degree or mba in finance...,gurgaon,1,3,ts gsa senior analyst chartered accountancy de...

#Criando a máquina virtual

In [ ]:
#Classificar cada valor único da base para facilitar a visualização

le = LabelEncoder()
df_train['salary'] = le.fit_transform(df_train['salary'])
le.classes_

array(['0to3', '10to15', '15to25', '25to50', '3to6', '6to10'],
      dtype=object)

In [ ]:
#Determinando quais são as variáveis determinantes e preenchendo as linhas vazias para não ficarem sem valores
#nesse caso o valor nulo - "" é diferente de sem valor NaN

df_train['merged'].fillna('', inplace=True)
df_train['location_cleaned'].fillna('', inplace=True)
df_test['merged'].fillna('', inplace=True)
df_test['location_cleaned'].fillna('', inplace=True)

train_features, validation_features, train_labels, validation_labels = train_test_split(
    df_train[['merged', 'location_cleaned', 'min_exp', 'max_exp']],
    df_train['salary'], test_size=0.20,
    stratify=df_train['salary'], random_state=75)

print('No. of sample texts in train_features:', len(train_features))
print('No. of sample texts in validation_features:', len(validation_features))
print('No. of sample labels in train_labels:', len(train_labels))
print('No. of sample labels in validation_labels:', len(validation_labels))

No. of sample texts in train_features: 15840
No. of sample texts in validation_features: 3961
No. of sample labels in train_labels: 15840
No. of sample labels in validation_labels: 3961

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from scipy.sparse import hstack, csr_matrix
from sklearn.preprocessing import StandardScaler
from scipy import sparse

# Unificando as colunas 'merged' e 'location_cleaned'
train_features_merged = train_features['merged'].fillna('')
train_features_loc = train_features['location_cleaned'].fillna('')
validation_features_merged = validation_features['merged'].fillna('')
validation_features_loc = validation_features['location_cleaned'].fillna('')
combined_train = train_features_merged + ' ' + train_features_loc
combined_validation = validation_features_merged + ' ' + validation_features_loc

# Aplicando TfidfVectorizer
tf1 = TfidfVectorizer(min_df=3, token_pattern=r'\w{3,}', ngram_range=(1,3), max_df=0.9)
tf2 = TfidfVectorizer(min_df=2, token_pattern=r'\w{3,}')

X_train_merged = tf1.fit_transform(combined_train)
X_train_loc = tf2.fit_transform(train_features_loc)

X_validation_merged = tf1.transform(combined_validation)
X_validation_loc = tf2.transform(validation_features_loc)

# Padronização dos valores numéricos
sc1 = StandardScaler()
X_train_MinExp = sc1.fit_transform(np.array(train_features['min_exp']).reshape(-1, 1))
X_validation_MinExp = sc1.transform(np.array(validation_features['min_exp']).reshape(-1, 1))

sc2 = StandardScaler()
X_train_MaxExp = sc2.fit_transform(np.array(train_features['max_exp']).reshape(-1, 1))
X_validation_MaxExp = sc2.transform(np.array(validation_features['max_exp']).reshape(-1, 1))

# Convertendo para matrizes esparsas
X_train_exp = csr_matrix(X_train_MinExp)
X_validation_exp = csr_matrix(X_validation_MinExp)
X_train_max_exp = csr_matrix(X_train_MaxExp)
X_validation_max_exp = csr_matrix(X_validation_MaxExp)

# Combinação das matrizes esparsas
merged_train = hstack((X_train_merged, X_train_loc, X_train_exp, X_train_max_exp))
merged_validation = hstack((X_validation_merged, X_validation_loc, X_validation_exp, X_validation_max_exp))

print("Shape of merged_train:", merged_train.shape)
print("Shape of merged_validation:", merged_validation.shape)

Shape of merged_train: (15840, 55198)
Shape of merged_validation: (3961, 55198)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import lightgbm as lgb

#definindo o dataset

train_data = lgb.Dataset(merged_train, label=train_labels)
test_data = lgb.Dataset(merged_validation, label=validation_labels)

# Definindo os parâmetros do modelo
params = {
    'objective': 'multiclass',
    'num_class': 6,
    'metric': 'multi_logloss',
    'num_leaves': 31,
    'learning_rate': 0.05,
    'feature_fraction': 0.9
}

# Treinando o modelo

lgbm = lgb.train(params=param, train_set=train_data, num_boost_round=100, valid_sets=[test_data])

y_pred_class = lgbm.predict(merged_validation)

/usr/local/lib/python3.10/dist-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")

[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.751865 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 31921
[LightGBM] [Info] Number of data points in the train set: 15840, number of used features: 3206
[LightGBM] [Info] Start training from score -1.808567
[LightGBM] [Info] Start training from score -1.481605
[LightGBM] [Info] Start training from score -1.568616
[LightGBM] [Info] Start training from score -2.531427
[LightGBM] [Info] Start training from score -1.947616
[LightGBM] [Info] Start training from score -1.724030
[1]	valid_0's multi_logloss: 1.70564
[2]	valid_0's multi_logloss: 1.67084
[3]	valid_0's multi_logloss: 1.63999
[4]	valid_0's multi_logloss: 1.61216
[5]	valid_0's multi_logloss: 1.58719
[6]	valid_0's multi_logloss: 1.56511
[7]	valid_0's multi_logloss: 1.54465
[8]	valid_0's multi_logloss: 1.52546
[9]	valid_0's multi_logloss: 1.50798
[10]	valid_0's multi_logloss: 1.49164
[11]	valid_0's multi_logloss: 1.47648
[12]	valid_0's multi_logloss: 1.4625
[13]	valid_0's multi_logloss: 1.44985
[14]	valid_0's multi_logloss: 1.43761
[15]	valid_0's multi_logloss: 1.4265
[16]	valid_0's multi_logloss: 1.416
[17]	valid_0's multi_logloss: 1.40601
[18]	valid_0's multi_logloss: 1.3968
[19]	valid_0's multi_logloss: 1.38778
[20]	valid_0's multi_logloss: 1.37962
[21]	valid_0's multi_logloss: 1.37175
[22]	valid_0's multi_logloss: 1.36423
[23]	valid_0's multi_logloss: 1.35725
[24]	valid_0's multi_logloss: 1.35105
[25]	valid_0's multi_logloss: 1.3448
[26]	valid_0's multi_logloss: 1.33881
[27]	valid_0's multi_logloss: 1.3331
[28]	valid_0's multi_logloss: 1.32771
[29]	valid_0's multi_logloss: 1.32257
[30]	valid_0's multi_logloss: 1.31748
[31]	valid_0's multi_logloss: 1.31298
[32]	valid_0's multi_logloss: 1.30901
[33]	valid_0's multi_logloss: 1.30486
[34]	valid_0's multi_logloss: 1.30113
[35]	valid_0's multi_logloss: 1.29767
[36]	valid_0's multi_logloss: 1.29389
[37]	valid_0's multi_logloss: 1.29076
[38]	valid_0's multi_logloss: 1.28768
[39]	valid_0's multi_logloss: 1.28469
[40]	valid_0's multi_logloss: 1.28194
[41]	valid_0's multi_logloss: 1.27899
[42]	valid_0's multi_logloss: 1.27633
[43]	valid_0's multi_logloss: 1.27396
[44]	valid_0's multi_logloss: 1.27181
[45]	valid_0's multi_logloss: 1.26939
[46]	valid_0's multi_logloss: 1.26738
[47]	valid_0's multi_logloss: 1.26536
[48]	valid_0's multi_logloss: 1.26327
[49]	valid_0's multi_logloss: 1.26153
[50]	valid_0's multi_logloss: 1.25956
[51]	valid_0's multi_logloss: 1.25753
[52]	valid_0's multi_logloss: 1.25593
[53]	valid_0's multi_logloss: 1.2543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's multi_logloss: 1.25252
[55]	valid_0's multi_logloss: 1.2513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's multi_logloss: 1.24979
[57]	valid_0's multi_logloss: 1.24846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's multi_logloss: 1.24709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's multi_logloss: 1.24554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's multi_logloss: 1.24432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's multi_logloss: 1.24303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's multi_logloss: 1.2417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's multi_logloss: 1.2406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's multi_logloss: 1.2394
[65]	valid_0's multi_logloss: 1.23825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's multi_logloss: 1.23724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's multi_logloss: 1.23651
[68]	valid_0's multi_logloss: 1.23566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's multi_logloss: 1.23472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's multi_logloss: 1.23385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's multi_logloss: 1.23308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's multi_logloss: 1.2322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's multi_logloss: 1.23127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's multi_logloss: 1.23055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's multi_logloss: 1.22994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's multi_logloss: 1.22968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's multi_logloss: 1.22878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's multi_logloss: 1.22808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's multi_logloss: 1.22753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's multi_logloss: 1.22682

In [ ]:


predictions = []
for x in y_pred_class:
    predictions.append(np.argmax(x))

accuracy = accuracy_score(validation_labels, predictions)
print('Accuracy:', accuracy)

Accuracy: 0.47816208028275686

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from scipy.sparse import hstack, csr_matrix
from sklearn.preprocessing import StandardScaler
from scipy import sparse

# Unificando as colunas 'merged' e 'location_cleaned'
train_features_merged = train_features['merged'].fillna('')
train_features_loc = train_features['location_cleaned'].fillna('')
validation_features_merged = validation_features['merged'].fillna('')
validation_features_loc = validation_features['location_cleaned'].fillna('')
combined_train = train_features_merged + ' ' + train_features_loc
combined_validation = validation_features_merged + ' ' + validation_features_loc

# Aplicando TfidfVectorizer
tf1 = TfidfVectorizer(min_df=3, token_pattern=r'\w{3,}', ngram_range=(1,3), max_df=0.9)
tf2 = TfidfVectorizer(min_df=2, token_pattern=r'\w{3,}')

X_train_merged = tf1.fit_transform(combined_train)
X_train_loc = tf2.fit_transform(train_features_loc)

X_validation_merged = tf1.transform(combined_validation)
X_validation_loc = tf2.transform(validation_features_loc)

# Padronização dos valores numéricos
sc1 = StandardScaler()
X_train_MinExp = sc1.fit_transform(np.array(train_features['min_exp']).reshape(-1, 1))
X_validation_MinExp = sc1.transform(np.array(validation_features['min_exp']).reshape(-1, 1))

sc2 = StandardScaler()
X_train_MaxExp = sc2.fit_transform(np.array(train_features['max_exp']).reshape(-1, 1))
X_validation_MaxExp = sc2.transform(np.array(validation_features['max_exp']).reshape(-1, 1))

# Convertendo para matrizes esparsas
X_train_exp = csr_matrix(X_train_MinExp)
X_validation_exp = csr_matrix(X_validation_MinExp)
X_train_max_exp = csr_matrix(X_train_MaxExp)
X_validation_max_exp = csr_matrix(X_validation_MaxExp)

# Combinação das matrizes esparsas
merged_train = hstack((X_train_merged, X_train_loc, X_train_exp, X_train_max_exp))
merged_validation = hstack((X_validation_merged, X_validation_loc, X_validation_exp, X_validation_max_exp))

print("Shape of merged_train:", merged_train.shape)
print("Shape of merged_validation:", merged_validation.shape)

Shape of merged_train: (15840, 55198)
Shape of merged_validation: (3961, 55198)

In [ ]:
#Convertendo os dados para o formato do LightGBM

train_data = lgb.Dataset(merged_train, label=train_labels)

# Definindo os parâmetros do modelo LightGBM
param = {'objective': 'multiclass',
         'num_iterations': 80,
         'learning_rate': 0.04,
         'num_leaves': 23,
         'max_depth': 7,
         'min_data_in_leaf': 28,
         'max_bin': 10,
         'min_data_in_bin': 3,
         'num_class': 6,
         'metric': 'multi_logloss'
         }

#Treinando o Modelo
lgbm_validation = lgb.train(params=param,
                            train_set=train_data,
                            num_boost_round=100)

predictions = lgbm.predict(merged_validation)

#Fazendo previsões no conjunto de teste
y_pred = lgbm_validation.predict(merged_validation)

y_pred_class = []
for x in predictions:
    y_pred_class.append(np.argmax(x))

y_pred_class = le.inverse_transform(y_pred_class)

/usr/local/lib/python3.10/dist-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")

[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.756146 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 31921
[LightGBM] [Info] Number of data points in the train set: 15840, number of used features: 3206
[LightGBM] [Info] Start training from score -1.808567
[LightGBM] [Info] Start training from score -1.481605
[LightGBM] [Info] Start training from score -1.568616
[LightGBM] [Info] Start training from score -2.531427
[LightGBM] [Info] Start training from score -1.947616
[LightGBM] [Info] Start training from score -1.724030
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [ ]:
df_sub = pd.DataFrame(data=y_pred_class, columns=['salary'])

df_sub

      salary
0     10to15
1     10to15
2       0to3
3      6to10
4       0to3
...      ...
3956   6to10
3957  15to25
3958    0to3
3959  15to25
3960  10to15

[3961 rows x 1 columns]